### ISSUE TITLE
add @HarshKhatore

### ISSUE THREAD

**Issue by HarshKhatore** [iiitv/getmein#139]
Add me as your member - [https://github.com/HarshKhatore](url)

**Comment by aviaryan** [comment]
Hey @HarshKhatore , are you a student of IIITV ?

**Comment by HarshKhatore** [comment]
Hi @aviaryan, no I am not from IIITV. But, I guess I can contribute to this repository.

**Comment by aviaryan** [comment]
Invited you to [Outsiders](https://github.com/orgs/iiitv/teams/outsiders) team. Check your email.
