### ISSUE TITLE
add @adityaprakash-bobby

### ISSUE THREAD

**Issue by adityaprakash-bobby** [iiitv/getmein#218]
Hi. Aditya from IIIT-Bhubaneswar. I would Love to contribute to the organization.

**Comment by aashutoshrathi** [comment]
Hi @adityaprakash-bobby 
We have created a portal for the same: https://getmein.glitch.me/

<blockquote><div><strong><a href="https://getmein.glitch.me/">Welcome to IIITV</a></strong></div><div>Portal to get an invite to IIITV Github organization</div></blockquote>

**Comment by aashutoshrathi** [comment]
Closing this issue. 😄
