### ISSUE TITLE
Can't connect with IIITV organization

### ISSUE THREAD

**Issue by 201851019-iiitv** [iiitv/getmein#251]
I am student of  IIITV  batch of 2022
. I have issues that I can't connect github Iiitvadodara organization of batch of 2022

**Comment by Monal5031** [comment]
Added you to org, Check your email for invitation.

**Comment by anshumanv** [comment]
Why is this?

When we're using the web version - https://getmein.glitch.me/

<blockquote><div><strong><a href="https://getmein.glitch.me/">Welcome to IIITV</a></strong></div><div>Portal to get an invite to IIITV Github
      organization</div></blockquote>

**Comment by Monal5031** [comment]
@anshumanv please fix the email system in the web version

**Comment by anshumanv** [comment]
cc @aashutoshrathi
