### ISSUE TITLE
add

### ISSUE THREAD

**Issue by CompDeMort** [iiitv/getmein#44]
add @codeFalconizer

**Comment by aviaryan** [comment]
Who is @CompDeMort  AND who is @codeFalconizer . Whom should I add ?

**Comment by CompDeMort** [comment]
CompDeMort is me,Kartik
CodeFalconizer is Jay

**Comment by CompDeMort** [comment]
Avi, pls add codeFalconizer as well. He is Jay.

**Comment by aviaryan** [comment]
added
