### ISSUE TITLE
getMeIn & websiteRelated 

### ISSUE THREAD

**Issue by geekyJock8** [iiitv/getmein#48]
hoping to help but the description on https://github.com/iiitv/college_website says that "The website will be static and has to be created by May 18, 2016" and today is 17th May

**Comment by aviaryan** [comment]
The work is going strong. Check the preview at http://iiitv.github.io/college_website . If you want to help, create a new issue at https://github.com/iiitv/college_website/issues .

**Comment by aviaryan** [comment]
I have sent you an invitation to join the org. Visit https://github.com/iiitv to accept it.
